# Generated by Django 5.0.3 on 2024-10-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sub_title',
            field=models.CharField(max_length=200, verbose_name='个人博客子标题'),
        ),
    ]
